#!/bin/bash
for mutual_info in 100 75 50; do
    if [[ "$mutual_info" -lt 100 ]]; then
        experiment_type=mutual_info_"$mutual_info";
    else
        experiment_type=10_runs;
    fi

    # for dataset in "wine" "contraceptive" "australian_credit" "german_credit" "iris" "pima" "wdbc"; do
    for dataset in  "heart"; do
        for classifier in "xgboost" "random_forest" "gradient_boosting" "svm"; do
        # for classifier in "random_forest"; do
            for run in 0 1 2 3 4 5 6 7 8 9; do
                folder=./resultados/"$dataset"/"$experiment_type"/"$classifier"
                mkdir -p  "$folder"
                python ./experimentos_baseline.py "$classifier" "$dataset" "$run" "$mutual_info"> "$folder"/"$dataset"_experimento_"$run"
                echo "Experimento com classificador $classifier dataset $dataset execução $run finalizado."
            done
        done
    done
done
