#!/bin/bash

# DATASETS="australian_credit german_credit heart pima wdbc contraceptive iris wine"
DATASETS="elipses"
#BASE_CLASSIFIERS="svm dt lr"
BASE_CLASSIFIERS="lr"

for dataset in $DATASETS; do
    #for mutual_info in 75 50; do
    for classifier in $BASE_CLASSIFIERS; do
        python supervised_clustering.py -d "$dataset" -b "$classifier" # -m "$mutual_info"
    done
    #done
done
